### PR TITLE
Changing all open calls to make sure they are open the minimum amount…

### PR DESCRIPTION
**Pull request by pmithrandir**
… of time and always closed properly

### CODE REVIEW

**Comment by jones139** [comment]
It seems to work ok, thank you!  (I have never got around to trying to work out what 'with' does in Python...)

**Review by jones139 — APPROVED** [review]

**Comment by jones139** [comment]
I think I spoke too soon.  I just tried to run curator_tools/makeOsdb.py and it crashed with this error:
`File "/home/graham/osd/OpenSeizureDatabase/curator_tools/./makeOsdDb.py", line 525, in <module>
    updateOsdbFile(fname, tcEventsLst,  args['config'], args['debug'])
  File "/home/graham/osd/OpenSeizureDatabase/curator_tools/./makeOsdDb.py", line 398, in updateOsdbFile
    libosd.tidy_db.updateDBSeizureTimes(cfgObj, osdb.getAllEvents(), debug)
  File "/home/graham/osd/OpenSeizureDatabase/curator_tools/./../libosd/tidy_db.py", line 206, in updateDBSeizureTimes
    seizureTimesObj = loadSeizureTimes(cfgObj, debug)
  File "/home/graham/osd/OpenSeizureDatabase/curator_tools/./../libosd/tidy_db.py", line 155, in loadSeizureTimes
    seizureTimesObj = readSeizureTimesObj(cfgObj, debug)
  File "/home/graham/osd/OpenSeizureDatabase/curator_tools/./../libosd/tidy_db.py", line 38, in readSeizureTimesObj
    for line in lines:
ValueError: I/O operation on closed file.`

Now I did run it on my older laptop, so it is possible that it ran out of memory and so is not your change, but would you mind having a look please?

**Comment by pmithrandir** [comment]
Hi,

I added a commit to resolve that issue. Sorry, I didn't realize that the CSV needed to access the file.

On my laptop, I'm not even able to reach that point when I launch the command. Looks like the \ in my password are not well interpreted. 

Any hint on where I can change my password to avoid that issue ?

Regards,
Pierre

**Comment by jones139** [comment]
You should be able to reset your password if you visit:  https://osdapi.ddns.net/

I wonder if the issue is with how the python script is encoding the password - maybe you have to escape it in the configuration file?

**Pull request merged**
